#!/bin/sh
PHP_FKOOMAN_INI_VERSION=0.2.0
PHP_FKOOMAN_JSON_VERSION=0.6.0
PHP_FKOOMAN_REST_VERSION=0.6.1
PHP_FKOOMAN_REST_PLUGIN_BASIC_VERSION=0.2.2
PHP_FKOOMAN_REST_PLUGIN_MELLON_VERSION=0.1.1
VPN_CERT_SERVICE_VERSION=0.1.10
VPN_USER_PORTAL_VERSION=0.1.9
